---
- name: Add elrepo repository
  yum:
    name: "epel-release"
    state: present

- name: Add remi-php
  yum_repository:
    name: remi-php
    description: Remi's PHP RPM repository for Enterprise Linux $releasever
    mirrorlist: "http://rpms.remirepo.net/enterprise/$releasever/php{{ php_depend_php_version | replace('.', '') }}/mirror"
    enabled: yes
    gpgcheck: 1
    gpgkey: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"

- name: Add remi-safe for additional dependencies
  yum_repository:
    name: remi-safe
    description: Safe Remi's RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: "http://cdn.remirepo.net/enterprise/$releasever/safe/mirror"
    enabled: yes
    gpgcheck: 1
    gpgkey: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"


- name: install packs php mysql
  yum:
    name: 
    - "php"
    - "php-mysql"
    state: present

