---
 - name: Configure httpd service
   become: true
   hosts: wordpress

   roles:
   - bertvv.httpd
   - php_depend
   - bertvv.mariadb
   - wp-install-config
   
   vars_files:
   - encrypted.yml

