---
# tasks file for wp-install-config

- name: Download WordPress
  get_url: 
    url: https://www.wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz 
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
  notify: restart httpd

- name: Send config file
  template: 
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php 
    mode: 0644
  notify: restart httpd
